=== crbothe/naoyadtk/YADTK/COMPILER/granules.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
##############################################################################
# This file is part of the YADTK Toolkit (Yet Another Dialogue Toolkit)
# Copyright © Jérôme Lehuen 2010-2015 - Jerome.Lehuen@univ-lemans.fr
#
# This software is governed by the CeCILL license under French law and
# abiding by the rules of distribution of free software. You can use,
# modify and/or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and INRIA (http://www.cecill.info).
#
# As a counterpart to the access to the source code and rights to copy,
# modify and redistribute granted by the license, users are provided only
# with a limited warranty and the software's author, the holder of the
# economic rights, and the successive licensors have only limited
# liability.
#
# In this respect, the user's attention is drawn to the risks associated
# with loading, using, modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean that it is complicated to manipulate, and that also
# therefore means that it is reserved for developers and experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards their
# requirements in conditions enabling the security of their systems and/or
# data to be ensured and, more generally, to use and operate it in the
# same conditions as regards security.
#
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.
##############################################################################

# This free software is registered at the Agence de Protection des Programmes.
# For further information or commercial purpose, please contact the author.
-->

<!ENTITY % typecode "(A1|A2|A3|A4|A5|A6|A7|A8|A9)" >
<!ENTITY % typebool "(TRUE|FALSE) 'FALSE'" >
<!ENTITY % typerole "IDREF 'nil'" >

<!-- !!! Doit être cohérent avec lexique.clp !!! -->
<!ENTITY % typegram "(NOM|GN|GV|PROP|NOUN|NP|VP|NONE) 'NONE'" >

<!ELEMENT granules (declare-feature|declare-metadata|declare-role|granule|group)* >

<!ELEMENT declare-feature EMPTY >
<!ATTLIST declare-feature id ID #REQUIRED >
<!ELEMENT declare-metadata EMPTY >
<!ATTLIST declare-metadata id ID #REQUIRED >
<!ELEMENT declare-role EMPTY >
<!ATTLIST declare-role id ID #REQUIRED >

<!ELEMENT granule (dependency*, constraint*, syntax*) >
<!ATTLIST granule
    concept ID #IMPLIED
    offers IDREFS #IMPLIED
    offerexpr CDATA #IMPLIED >

<!ELEMENT dependency EMPTY >
<!ATTLIST dependency
    expected IDREFS #IMPLIED
    required IDREFS #IMPLIED
    rejected IDREFS #IMPLIED
    id %typecode; #REQUIRED
    role %typerole;
    flex %typebool;
    mult %typebool;
    tag  %typegram; >

<!ELEMENT constraint EMPTY >
<!ATTLIST constraint test CDATA #IMPLIED >

<!ELEMENT syntax EMPTY >
<!ATTLIST syntax
    pattern CDATA #IMPLIED
    example CDATA #IMPLIED
    metadata IDREFS #IMPLIED
    gen %typebool;
    toA1 IDREFS #IMPLIED
    toA2 IDREFS #IMPLIED
    toA3 IDREFS #IMPLIED
    toA4 IDREFS #IMPLIED
    toA5 IDREFS #IMPLIED
    toA6 IDREFS #IMPLIED
    toA7 IDREFS #IMPLIED
    toA8 IDREFS #IMPLIED
    toA9 IDREFS #IMPLIED >

<!ELEMENT group (entity+) >
<!ATTLIST group
	concept ID #REQUIRED
	offers IDREFS #IMPLIED >

<!ELEMENT entity EMPTY >
<!ATTLIST entity
	pattern CDATA #REQUIRED
	value CDATA #IMPLIED
	metadata IDREFS #IMPLIED
	gen (TRUE|FALSE) 'TRUE' >

=== crbothe/naoyadtk/YADTK/COMPILER/EMPTY/YASP_data/granules.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE granules SYSTEM "../../../YADTK/COMPILER/granules.dtd" [

<!ENTITY granules-1 SYSTEM "granules-1.xml">
<!ENTITY granules-2 SYSTEM "granules-2.xml">

]>

<granules>
	
<!-- Do not remove the following lines -->
    
    <declare-feature id="NONE"/>
    <declare-feature id="A1"/>
    <declare-feature id="A2"/>
    <declare-feature id="A3"/>
    <declare-feature id="A4"/>
    <declare-feature id="A5"/>
    <declare-feature id="A6"/>
    <declare-feature id="A7"/>
    <declare-feature id="A8"/>
    <declare-feature id="A9"/>
    
    <declare-metadata id="mode:neg"/>
    <declare-metadata id="mode:inter"/>
    <declare-metadata id="morpho:masc"/>
    <declare-metadata id="morpho:fem"/>
    <declare-metadata id="morpho:sing"/>
    <declare-metadata id="morpho:plu"/>

	<!-- User definitions -->

	&granules-1;
	&granules-2;
	
</granules>

=== crbothe/naoyadtk/APPLICATIONS/DEMO_NAO/YASP_data/granules.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE granules SYSTEM "../../../YADTK/COMPILER/granules.dtd" [

<!ENTITY granules-nao SYSTEM "granules-nao.xml">

]>

<granules>
	
	<!-- Do not remove the following lines -->

	<declare-feature id="NONE"/>
	<declare-feature id="A1"/>
	<declare-feature id="A2"/>
	<declare-feature id="A3"/>
	<declare-feature id="A4"/>
	<declare-feature id="A5"/>
	<declare-feature id="A6"/>
	<declare-feature id="A7"/>
	<declare-feature id="A8"/>
	<declare-feature id="A9"/>

	<!-- User definitions -->

	&granules-nao;
		
</granules>
